### ISSUE TITLE
Can't download the data.

### ISSUE THREAD

**Issue by htw970202** [shmsw25/GraphRetriever#1]
Hello, 

I want to reproduce your experiment, but I can't download the data. 
How can I get it?

**Comment by shmsw25** [comment]
Hi,

You should be able to download the data by following [this section](https://github.com/shmsw25/GraphRetriever#0-download-qa-data). Please download one dataset with one command line (by choosing one of three datasets).

**Comment by htw970202** [comment]
First of all, thank you for your answer. I've already tried the line, but it didn't work.

I don't think the "https://nlp.cs.washington.edu/ambigqa/data/" site exists.

**error code:**

wget https://nlp.cs.washington.edu/ambigqa/data/{webquestions|nq|triviaqa}.zip
ns|nq|triviaqa}.zipbash: nq: command not found
bash: triviaqa}.zip: command not found
--2023-01-25 05:05:06--  https://nlp.cs.washington.edu/ambigqa/data/%7Bwebquestions
Resolving [nlp.cs.washington.edu](http://nlp.cs.washington.edu/) ([nlp.cs.washington.edu](http://nlp.cs.washington.edu/))... 128.208.3.120, 2607:4000:200:12::78
Connecting to [nlp.cs.washington.edu](http://nlp.cs.washington.edu/) ([nlp.cs.washington.edu](http://nlp.cs.washington.edu/))|128.208.3.120|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-01-25 05:05:07 ERROR 404: Not Found.

**Comment by shmsw25** [comment]
You need to do run the command line separately for each dataset. Please try the following:
```bash
wget https://nlp.cs.washington.edu/ambigqa/data/webquestions.zip
wget https://nlp.cs.washington.edu/ambigqa/data/nq.zip
wget https://nlp.cs.washington.edu/ambigqa/data/triviaqa.zip
```

**Comment by htw970202** [comment]
Oh, I see, I made a mistake. Thank you.
